USE cloud_album;

CREATE TABLE IF NOT EXISTS t_review_setting (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '固定为1的审核设置主键',
    auto_approve_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否自动审核通过',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容审核设置表';
